# Importing Numpy


In [2]:
import numpy as np

# Basics


In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Get Dimension
b.ndim

2

In [7]:
# Get Shape
b.shape

(3, 3)

In [8]:
# Get Type
a.dtype

dtype('int32')

In [9]:
# Get Size
a.itemsize

4

## Accessing/Changing specific elements, rows, columns etc

In [12]:
c = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [15]:
# Get specific element [r,c] { it has 0 indexing}
c[1,5]

14

In [14]:
c[0,6]

7

In [17]:
# Get specific row
print(c[0,:])

[1 2 3 4 5 6 7 8]


In [19]:
# getting specific column
print(c[:,3])

[ 4 12]


In [24]:
# Advance iteration { startIndex :endIndex:stepSize }
print(c[:,0::2])

[[ 1  3  5  7]
 [ 9 11 13 15]]


In [26]:
# changing values

c[1,4]=90
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 90 14 15 16]]


## Initializing different types of array

In [28]:
# All zeroes
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
# All Ones
one = np.ones(6 , dtype='int16')
print(one)

[1 1 1 1 1 1]


In [32]:
# Any arbitrary value
arb = np.full((2,3),44)
print(arb)

[[44 44 44]
 [44 44 44]]


In [33]:
# cloning an array with different values
cln = np.full_like(c,55)
print(cln)

[[55 55 55 55 55 55 55 55]
 [55 55 55 55 55 55 55 55]]


In [34]:
# random decimal values
np.random.rand(4,5)

array([[0.73730075, 0.05807844, 0.48229535, 0.92939599, 0.63049914],
       [0.93796532, 0.62443038, 0.54755785, 0.41193455, 0.95383305],
       [0.81783985, 0.74656619, 0.23458181, 0.37970801, 0.51243091],
       [0.97004153, 0.01589869, 0.95984061, 0.09751401, 0.63233894]])

In [35]:
np.random.randint(-4,9, size=(4,5))  # 9 is not included

array([[ 3, -3,  2,  2,  2],
       [ 4,  6,  2, -1,  6],
       [-2,  3,  6,  0,  5],
       [ 7,  0,  3,  4,  6]])

In [36]:
# Identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [3]:
arr=np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [4]:
# Repeating an array
arr=np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


##  Creating a predefined array(array's image is given and we need to implement it)

In [13]:
output = np.ones((5,5) , dtype='int16')
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
z = np.zeros((3,3) , dtype='int16')
z[1,1] = 9
print(z)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


### Combining these 2 arrays to form a single array

In [14]:
output[1:4,1:4] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Array Mathematics

In [15]:
arr = np. array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [17]:
arr+2

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
arr-2

array([-1,  0,  1,  2,  3,  4,  5])

In [21]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [22]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [25]:
brr = np.array([2,3,4,5,6,7,8])
arr+brr

array([ 3,  5,  7,  9, 11, 13, 15])

In [27]:
arr**2

array([ 1,  4,  9, 16, 25, 36, 49])

In [28]:
## Take sin of all values
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ])

### Linear Algebra

In [29]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a,'\n\n')
print(b)

[[1. 1. 1.]
 [1. 1. 1.]] 


[[2 2]
 [2 2]
 [2 2]]


In [30]:
## Multiplying two matrices
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [32]:
## Finding Determinant

c = np.identity(5)
np.linalg.det(c)

1.0

In [ ]:
'''
   Some other operations to look at (read official documentation)
       1. Trace
       2. Singular Vector Decomposition
       3. Eigen Values
       4. Matrix Norm
       5. Inverse of a matrix
'''

### Statistics

In [34]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [35]:
np.min(stats)

1

In [36]:
np.max(stats)

6

In [37]:
np.mean(stats)

3.5

In [39]:
np.max(stats , axis=1) # Row wise

array([3, 6])

In [40]:
np.max(stats , axis=0) # Column wise 

array([4, 5, 6])

In [41]:
 np.sum(stats)

21

## Reorganizing Arrays

In [43]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [46]:
after = before.reshape((1,8))
print(after)

[[1 2 3 4 5 6 7 8]]


In [47]:
after2 = before.reshape((2,2,2))  # No. of elements (rxc) must be same
print(after2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
# Vertically stacking arrays
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])

vs = np.vstack([v1,v2,v1,v2,v1])  # Size of all arrays must be same
print(vs)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [53]:
# Horizontal stack
h1 = np.array([1,2,3,4,5])
h2 = np.array([6,7,8,9,10,11])

hs = np.hstack([h1,h2,h1,h2])  # Size of the array doesn't matter
print(hs)

[ 1  2  3  4  5  6  7  8  9 10 11  1  2  3  4  5  6  7  8  9 10 11]


# Misc

## Loading Data from files

In [60]:
data = np.genfromtxt(r'numpy dummy data.txt',delimiter=',')  # De-Limiter is the character which is inserted between values.
print(data)


[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [61]:
fileData = data.astype('int32')
print(fileData)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean masking and advanced Indexing

In [62]:
fileData>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [64]:
fileData[fileData>50]  # Prints values from the data which are greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [66]:
fileData[(fileData>50) & (fileData<100)]

array([75, 75, 55, 78, 76, 88])

In [67]:
((fileData>50) & (fileData<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [68]:
(~(fileData>50) & (fileData<100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])